data:
  dropna: true
  input_col: OPENADMET_SMILES
  target_cols:
  - y
  test_resource: /home/urakarina/openadmet-anvil-repro/tdc_data/clearance_microsome_az/test.parquet
  train_resource: /home/urakarina/openadmet-anvil-repro/tdc_data/clearance_microsome_az/seed_1/train.parquet
  type: intake
  val_resource: /home/urakarina/openadmet-anvil-repro/tdc_data/clearance_microsome_az/seed_1/valid.parquet
metadata:
  authors: openadmet-anvil-repro
  biotargets:
  - clearance_microsome_az
  build_number: 0
  description: TDC ADMET_Group clearance_microsome_az seed 1
  driver: sklearn
  email: k@mail.ru
  name: clearance_microsome_az__ChemPropModel__chemprop__chemprop_small
  tag: tdc__clearance_microsome_az__seed1__ChemPropModel__chemprop__chemprop_small
  tags:
  - tdc
  - admet_group
  version: v1
procedure:
  feat:
    params: {}
    type: ChemPropFeaturizer
  model:
    params: {}
    type: ChemPropModel
  split:
    params:
      random_state: 42
      test_size: 0.0
      train_size: 1.0
      val_size: 0.0
    type: ShuffleSplitter
  train:
    params:
      batch_size: 50
      lr: 0.0005
      max_epochs: 30
    type: LightningTrainer
report:
  eval:
  - params: {}
    type: RegressionMetrics
  - params:
      n_repeats: 5
      n_splits: 5
      random_state: 42
    type: PytorchLightningRepeatedKFoldCrossValidation
