data:
  anvil_dir: file:///home/urakarina/openadmet-anvil-repro/tdc_recipes/ames/seed_1/ChemPropModel/chemprop/chemprop_small
  cat_entry: null
  dropna: true
  input_col: OPENADMET_SMILES
  resource: null
  target_cols:
  - y
  test_resource: /home/urakarina/openadmet-anvil-repro/tdc_data/ames/test.parquet
  train_resource: /home/urakarina/openadmet-anvil-repro/tdc_data/ames/seed_1/train.parquet
  type: intake
  val_resource: /home/urakarina/openadmet-anvil-repro/tdc_data/ames/seed_1/valid.parquet
metadata:
  authors: openadmet-anvil-repro
  biotargets:
  - ames
  build_number: 0
  description: TDC ADMET_Group ames seed 1
  driver: sklearn
  email: k@mail.ru
  name: ames__ChemPropModel__chemprop__chemprop_small
  tag: tdc__ames__seed1__ChemPropModel__chemprop__chemprop_small
  tags:
  - tdc
  - admet_group
  version: v1
procedure:
  ensemble: null
  feat:
    params: {}
    type: ChemPropFeaturizer
  model:
    freeze_weights: null
    param_path: null
    params: {}
    serial_path: null
    type: ChemPropModel
  split:
    params:
      random_state: 42
      test_size: 0.0
      train_size: 1.0
      val_size: 0.0
    type: ShuffleSplitter
  train:
    params:
      accelerator: gpu
      batch_size: 50
      devices: 1
      lr: 0.0005
      max_epochs: 30
    type: LightningTrainer
  transform: null
report:
  eval:
  - params: {}
    type: ClassificationMetrics
  - params:
      n_repeats: 5
      n_splits: 5
      random_state: 42
    type: PytorchLightningRepeatedKFoldCrossValidation
